In [9]:
M = Float64[log(sqrt(i^2+j^2)) for i=1:1000,j=1:1000];

In [10]:
tic()
U,S,V = svd(M)
toc()

elapsed time: 1

1.518473017

.518473017 seconds


In [3]:
U*diagm(S)*V'

5x5 Array{Float64,2}:
 0.346574  0.804719  1.15129  1.41661  1.62905
 0.804719  1.03972   1.28247  1.49787  1.68365
 1.15129   1.28247   1.44519  1.60944  1.76318
 1.41661   1.49787   1.60944  1.73287  1.85679
 1.62905   1.68365   1.76318  1.85679  1.95601

In [4]:
k=3
U = U[:,1:k]
V = V[:,1:k]
S = S[1:k]

3-element Array{Float64,1}:
 7.38064  
 0.805432 
 0.0517735

In [5]:
U*diagm(S)*V'

5x5 Array{Float64,2}:
 0.34665   0.804427  1.15152  1.41681  1.62884
 0.804427  1.04084   1.28159  1.4971   1.68444
 1.15152   1.28159   1.44589  1.61001  1.76257
 1.41681   1.4971    1.61001  1.73345  1.85621
 1.62884   1.68444   1.76257  1.85621  1.95659

In [6]:
function my_SVD(M::Array{Float64,2},k::Int)
    m = size(M,1)
    X = randn(k,m)
    Y=X*M
    q,r = qr(Y')
    Z = M*q
    U,S,V = svd(Z)
    return U,S,V'*q'
end


my_SVD (generic function with 1 method)

In [14]:
tic()
U1,S1,V1 = my_SVD(M,10)
toc()
S1

elapsed time: 0.

10-element Array{Float64,1}:
 6556.48     
  231.701    
   44.4527   
   13.2783   
    4.82515  
    1.94818  
    0.827713 
    0.377232 
    0.142052 
    0.0545914

027487732 seconds


In [12]:
S

1000-element Array{Float64,1}:
 6556.48       
  231.702      
   44.4535     
   13.279      
    4.82779    
    1.95767    
    0.847226   
    0.381236   
    0.175402   
    0.0816056  
    0.038121   
    0.0178019  
    0.00828895 
    ⋮          
    6.49917e-13
    6.49917e-13
    6.49917e-13
    6.49917e-13
    6.49917e-13
    6.49917e-13
    6.49917e-13
    6.49917e-13
    4.00422e-13
    3.79584e-13
    2.56836e-13
    1.07696e-13

In [21]:
T = Float64[M[i,j]*M[k,l] for i=1:5,j=1:5,k=1:5,l=1:5];

In [22]:
MT = reshape(T,(5^2,5^2));

In [23]:
UT,ST,VT = my_SVD(MT,5)

(
25x5 Array{Float64,2}:
 -0.0466788   0.0555878  -0.0113012   0.0188997   0.0186714  
 -0.108385   -0.0475019   0.110838   -0.180749    0.11415    
 -0.155064    0.0578636  -0.0514717   0.128821    0.237349   
 -0.190798   -0.274222   -0.198298    0.148266    0.191037   
 -0.219411   -0.082637    0.104055    0.320787   -0.280721   
 -0.108385   -0.0475019   0.110838   -0.180749    0.11415    
 -0.140037   -0.0443963  -0.115882    0.111222   -0.261799   
 -0.172732    0.0743503  -0.346007   -0.243295   -0.000497853
 -0.201743   -0.0511329  -0.0593166  -0.120582   -0.403451   
 -0.226765    0.0742568  -0.227212   -0.116778    0.209962   
 -0.155064    0.0578636  -0.0514717   0.128821    0.237349   
 -0.172732    0.0743503  -0.346007   -0.243295   -0.000497853
 -0.194647    0.178213    0.347123   -0.0567602   0.274982   
 -0.21677     0.161352    0.351374   -0.137392    0.024769   
 -0.237477    0.452842   -0.0390519   0.267641   -0.0199194  
 -0.190798   -0.274222   -0.198298    0.14826

In [24]:
UTb = reshape(UT,(5,5,5))

5x5x5 Array{Float64,3}:
[:, :, 1] =
 -0.0466788  -0.108385  -0.155064  -0.190798  -0.219411
 -0.108385   -0.140037  -0.172732  -0.201743  -0.226765
 -0.155064   -0.172732  -0.194647  -0.21677   -0.237477
 -0.190798   -0.201743  -0.21677   -0.233394  -0.250084
 -0.219411   -0.226765  -0.237477  -0.250084  -0.263449

[:, :, 2] =
  0.0555878  -0.0475019  0.0578636  -0.274222   -0.082637 
 -0.0475019  -0.0443963  0.0743503  -0.0511329   0.0742568
  0.0578636   0.0743503  0.178213    0.161352    0.452842 
 -0.274222   -0.0511329  0.161352   -0.471423   -0.190066 
 -0.082637    0.0742568  0.452842   -0.190066   -0.0625557

[:, :, 3] =
 -0.0113012   0.110838   -0.0514717  -0.198298    0.104055 
  0.110838   -0.115882   -0.346007   -0.0593166  -0.227212 
 -0.0514717  -0.346007    0.347123    0.351374   -0.0390519
 -0.198298   -0.0593166   0.351374    0.171518    0.187767 
  0.104055   -0.227212   -0.0390519   0.187767   -0.190116 

[:, :, 4] =
  0.0188997  -0.180749   0.128821    0.148266   0.